# Basic
title: 半甜不要腻
subtitle: halfsuger  
description: welcome to my page
# 头像里面的标题
avatarTitle: CuteJ
# 头像里面的描述
avatarDesc: Come on!
url: "http://alwaysPKU.github.io/"

#阅读量
leancloud:
  enable: true
  app_id: TKFClR9mFN7woW6NwHuQAxDb-gzGzoHsz
  app_key: 8NibCKPlTVw5om1DF1dMaQvN

# Comment
#comment:
#    disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: no 
    github: alwaysPKU
    # twitter: 
    mail: v.cpp@pku.edu.cn

# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-84134159-3   
#    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: archive, url: '/archive'}   
    - {title: 分类, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
#gems: [jekyll-paginate,jekyll-sitemap]
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"


